pipeline {
    agent any

    stages {
        stage('Compile stage') {
            steps {
                echo 'Building..'
		withMaven(maven: 'maven_3_0_5'){
		    bat 'mvn clean compile'	
		}

            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
		withMaven(maven: 'maven_3_0_5'){
		    bat 'mvn test'	
		}
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
		withMaven(maven: 'maven_3_0_5'){
		    bat 'mvn deploy'	
		}
            }
        }
    }
}