pipeline {
    agent any

    stages {
        stage('Compile stage') {
            steps {
                echo 'Building..'
		withMaven(maven: 'maven_3_0_5'){
		    cd 'energy-web-services'
		    sh 'mvn clean compile'	
		}

            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
		withMaven(maven: 'maven_3_0_5'){
		    cd 'energy-web-services'	
		    sh 'mvn test'	
		}
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
		withMaven(maven: 'maven_3_0_5'){
		    cd 'energy-web-services' 
		    sh 'mvn deploy'	
		}
            }
        }
    }
}